name: ai-pricing-demo
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - sqlalchemy==2.0.23
    - pydantic==2.5.0
    - python-multipart==0.0.6
    - reportlab==4.0.7
    - pandas==2.0.3
    - numpy==1.24.3
    - python-jose==3.3.0
    - passlib==1.7.4
    - bcrypt==4.1.2
    - aiofiles==23.2.1
    - openpyxl==3.1.2
    - python-dotenv==1.0.0
    - pytest==8.4.2  # include pytest for CI/dev
